import Head from "next/head";
import { useRouter } from "next/router";
import en from "../public/locales/en/english.json";
import es from "../public/locales/es/espanol.json";
import Link from "next/link";
import "../components/i18n";

import Image from "next/image";

import { AnimatePresence, motion as m } from "framer-motion";

import Layout from "../components/Layout";


export default function Home() {
  const { locale, locales, push } = useRouter();

  const t = locale === "es" ? es : en;

  const handleClick = (l) => () => {
    push("/", undefined, { locale: l });
  };

  return (
    <>

  <Head>
  
    <title>The Surf House</title>
    <meta name="description" content="Vivir la cuidad de otra manera"/>
    <meta property="og:title" content={t.seo.title }/>
    <link rel="icon" href="/favicon.ico"/>
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
    <link rel="manifest" href="/site.webmanifest"></link>

  </Head>
  <Layout />

      {/* <m.div 
      initial={{y: "100%", }} 
      animate={{y: "0%", opacity:1}} 
      transition={{ duration:0.75 , ease:'easeInOut' }} 
      exit={{opacity:1}}
      className="text-gray-900 absolute top-0 left-0 w-screen h-screen lg:h-screen bg-[#011C35] lg:px-32 overflow-hidden ">
        <Head>
          <title>SurfHouse Website</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main> */}
      {/* 
        <div className="absolute right-0 top-0 h-80 w-80 "> */}
      {/* <!-- ribbon --> */}
      {/* 
              <div className="absolute left-[-35px] top-[35px] w-[450px] transform rotate-45 bg-[#FF3B18] text-center text-white font-semibold py-8">
              <Image 
                src={logos}
                alt="logos"
                objectFit='cover'
                objectPosition=''
                fill='contain'
              />
              </div> */}

      {/* <!-- end ribbon --> */}
      {/* </div>
          
          <div className='lg:my-96 mt-20 p-1'>
          */}

      {/* <AnimatePresence>
              <m.h1 animate={{y:0}}
                    initial={{y:"100%"}}
                    transition={{ delay: 0.5, duration: 0.5}} 
                    className='text-5xl text-center lg:text-left lg:text-9xl'>   SURFHOUSE</m.h1>
            </AnimatePresence> */}
      {/*           
            <div className='text-xl md:text-5xl text-white absolute align-top md:mt-12 p-0 md:ml-16'>

              <m.p
              className='ml-7 mt-3 md:mt-0 md:ml-1 md:mb-1'
               animate={{rotate:[0,-90]}}>the</m.p>
            </div>
            <div className='text-5xl md:text-9xl text-white aboslute'>
              <AnimatePresence> <m.p
                initial={{opacity:0 }}
                animate={{opacity:1}}
                transition={{ease:'easeIn', duration:1, delay:1}}
                className=' ml-14 md:ml-32 '>SURF</m.p>
              </AnimatePresence>
             <AnimatePresence>
              <m.p 
              animate={{y:0 ,opacity:1 }}
              initial={{y:"100%",opacity:0}}
              transition={{ delay:1.5, duration: 0.5}} 
              className='ml-3 md:ml-2 text-WHITE'>HOUSE</m.p>
             </AnimatePresence>
              
            </div>
            <div className='hidden lg:inline-flex'>
            <FadeInMenu />
            </div>
           
          </div>
        
        </main>
       
      </m.div> */}
    </>
  );
}
